//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.03 at 09:04:29 AM CDT 
//


package org.sw.marketing.data.website;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.sw.marketing.data.website package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.sw.marketing.data.website
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Data }
     * 
     */
    public Data createData() {
        return new Data();
    }

    /**
     * Create an instance of {@link Skin }
     * 
     */
    public Skin createSkin() {
        return new Skin();
    }

    /**
     * Create an instance of {@link Data.Website }
     * 
     */
    public Data.Website createDataWebsite() {
        return new Data.Website();
    }

    /**
     * Create an instance of {@link Environment }
     * 
     */
    public Environment createEnvironment() {
        return new Environment();
    }

    /**
     * Create an instance of {@link org.sw.marketing.data.website.Role }
     * 
     */
    public org.sw.marketing.data.website.Role createRole() {
        return new org.sw.marketing.data.website.Role();
    }

    /**
     * Create an instance of {@link Message }
     * 
     */
    public Message createMessage() {
        return new Message();
    }

    /**
     * Create an instance of {@link Skin.Role }
     * 
     */
    public Skin.Role createSkinRole() {
        return new Skin.Role();
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link Data.Website.Template }
     * 
     */
    public Data.Website.Template createDataWebsiteTemplate() {
        return new Data.Website.Template();
    }

    /**
     * Create an instance of {@link Data.Website.Page }
     * 
     */
    public Data.Website.Page createDataWebsitePage() {
        return new Data.Website.Page();
    }

}
