//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.03 at 09:32:45 AM CST 
//


package org.sw.marketing.data.calendar;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="environment">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="componentId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="screenName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="serverName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="assets" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="contactName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="contactEmail" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="calendar" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="creationTimestamp" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="prettyUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="skinUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="skinSelector" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="messagePublicFormIntro" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="messagePublicFormClosing" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="deleted" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="message" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="subtype" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="label" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="questionId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="questionNumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="required" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="user">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="emailAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="firstName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="lastName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="pictureUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="active" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                   &lt;element name="admin" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "environment",
    "calendar",
    "message",
    "user"
})
@XmlRootElement(name = "data")
public class Data {

    @XmlElement(required = true)
    protected Data.Environment environment;
    protected List<Data.Calendar> calendar;
    protected List<Data.Message> message;
    @XmlElement(required = true)
    protected Data.User user;

    /**
     * Gets the value of the environment property.
     * 
     * @return
     *     possible object is
     *     {@link Data.Environment }
     *     
     */
    public Data.Environment getEnvironment() {
        return environment;
    }

    /**
     * Sets the value of the environment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Data.Environment }
     *     
     */
    public void setEnvironment(Data.Environment value) {
        this.environment = value;
    }

    /**
     * Gets the value of the calendar property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the calendar property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCalendar().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Data.Calendar }
     * 
     * 
     */
    public List<Data.Calendar> getCalendar() {
        if (calendar == null) {
            calendar = new ArrayList<Data.Calendar>();
        }
        return this.calendar;
    }

    /**
     * Gets the value of the message property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the message property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMessage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Data.Message }
     * 
     * 
     */
    public List<Data.Message> getMessage() {
        if (message == null) {
            message = new ArrayList<Data.Message>();
        }
        return this.message;
    }

    /**
     * Gets the value of the user property.
     * 
     * @return
     *     possible object is
     *     {@link Data.User }
     *     
     */
    public Data.User getUser() {
        return user;
    }

    /**
     * Sets the value of the user property.
     * 
     * @param value
     *     allowed object is
     *     {@link Data.User }
     *     
     */
    public void setUser(Data.User value) {
        this.user = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="creationTimestamp" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="prettyUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="skinUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="skinSelector" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="messagePublicFormIntro" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="messagePublicFormClosing" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="deleted" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id",
        "creationTimestamp",
        "type",
        "title",
        "prettyUrl",
        "skinUrl",
        "skinSelector",
        "messagePublicFormIntro",
        "messagePublicFormClosing",
        "deleted"
    })
    public static class Calendar {

        protected long id;
        @XmlElement(required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar creationTimestamp;
        @XmlElement(required = true)
        protected String type;
        @XmlElement(required = true)
        protected String title;
        @XmlElement(required = true)
        protected String prettyUrl;
        @XmlElement(required = true)
        protected String skinUrl;
        @XmlElement(required = true)
        protected String skinSelector;
        @XmlElement(required = true)
        protected String messagePublicFormIntro;
        @XmlElement(required = true)
        protected String messagePublicFormClosing;
        protected boolean deleted;

        /**
         * Gets the value of the id property.
         * 
         */
        public long getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         */
        public void setId(long value) {
            this.id = value;
        }

        /**
         * Gets the value of the creationTimestamp property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getCreationTimestamp() {
            return creationTimestamp;
        }

        /**
         * Sets the value of the creationTimestamp property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setCreationTimestamp(XMLGregorianCalendar value) {
            this.creationTimestamp = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

        /**
         * Gets the value of the title property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTitle() {
            return title;
        }

        /**
         * Sets the value of the title property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTitle(String value) {
            this.title = value;
        }

        /**
         * Gets the value of the prettyUrl property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrettyUrl() {
            return prettyUrl;
        }

        /**
         * Sets the value of the prettyUrl property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrettyUrl(String value) {
            this.prettyUrl = value;
        }

        /**
         * Gets the value of the skinUrl property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSkinUrl() {
            return skinUrl;
        }

        /**
         * Sets the value of the skinUrl property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSkinUrl(String value) {
            this.skinUrl = value;
        }

        /**
         * Gets the value of the skinSelector property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSkinSelector() {
            return skinSelector;
        }

        /**
         * Sets the value of the skinSelector property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSkinSelector(String value) {
            this.skinSelector = value;
        }

        /**
         * Gets the value of the messagePublicFormIntro property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMessagePublicFormIntro() {
            return messagePublicFormIntro;
        }

        /**
         * Sets the value of the messagePublicFormIntro property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMessagePublicFormIntro(String value) {
            this.messagePublicFormIntro = value;
        }

        /**
         * Gets the value of the messagePublicFormClosing property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMessagePublicFormClosing() {
            return messagePublicFormClosing;
        }

        /**
         * Sets the value of the messagePublicFormClosing property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMessagePublicFormClosing(String value) {
            this.messagePublicFormClosing = value;
        }

        /**
         * Gets the value of the deleted property.
         * 
         */
        public boolean isDeleted() {
            return deleted;
        }

        /**
         * Sets the value of the deleted property.
         * 
         */
        public void setDeleted(boolean value) {
            this.deleted = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="componentId" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="screenName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="serverName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="assets" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="contactName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="contactEmail" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "componentId",
        "screenName",
        "serverName",
        "assets",
        "contactName",
        "contactEmail"
    })
    public static class Environment {

        protected int componentId;
        @XmlElement(required = true)
        protected String screenName;
        @XmlElement(required = true)
        protected String serverName;
        @XmlElement(required = true)
        protected String assets;
        @XmlElement(required = true)
        protected String contactName;
        @XmlElement(required = true)
        protected String contactEmail;

        /**
         * Gets the value of the componentId property.
         * 
         */
        public int getComponentId() {
            return componentId;
        }

        /**
         * Sets the value of the componentId property.
         * 
         */
        public void setComponentId(int value) {
            this.componentId = value;
        }

        /**
         * Gets the value of the screenName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getScreenName() {
            return screenName;
        }

        /**
         * Sets the value of the screenName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setScreenName(String value) {
            this.screenName = value;
        }

        /**
         * Gets the value of the serverName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getServerName() {
            return serverName;
        }

        /**
         * Sets the value of the serverName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setServerName(String value) {
            this.serverName = value;
        }

        /**
         * Gets the value of the assets property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAssets() {
            return assets;
        }

        /**
         * Sets the value of the assets property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAssets(String value) {
            this.assets = value;
        }

        /**
         * Gets the value of the contactName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContactName() {
            return contactName;
        }

        /**
         * Sets the value of the contactName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContactName(String value) {
            this.contactName = value;
        }

        /**
         * Gets the value of the contactEmail property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContactEmail() {
            return contactEmail;
        }

        /**
         * Sets the value of the contactEmail property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContactEmail(String value) {
            this.contactEmail = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="subtype" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="label" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="questionId" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="questionNumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="required" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "type",
        "subtype",
        "label",
        "questionId",
        "questionNumber",
        "required"
    })
    public static class Message {

        @XmlElement(required = true)
        protected String type;
        @XmlElement(required = true)
        protected String subtype;
        @XmlElement(required = true)
        protected String label;
        protected long questionId;
        protected int questionNumber;
        protected boolean required;

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

        /**
         * Gets the value of the subtype property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSubtype() {
            return subtype;
        }

        /**
         * Sets the value of the subtype property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSubtype(String value) {
            this.subtype = value;
        }

        /**
         * Gets the value of the label property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLabel() {
            return label;
        }

        /**
         * Sets the value of the label property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLabel(String value) {
            this.label = value;
        }

        /**
         * Gets the value of the questionId property.
         * 
         */
        public long getQuestionId() {
            return questionId;
        }

        /**
         * Sets the value of the questionId property.
         * 
         */
        public void setQuestionId(long value) {
            this.questionId = value;
        }

        /**
         * Gets the value of the questionNumber property.
         * 
         */
        public int getQuestionNumber() {
            return questionNumber;
        }

        /**
         * Sets the value of the questionNumber property.
         * 
         */
        public void setQuestionNumber(int value) {
            this.questionNumber = value;
        }

        /**
         * Gets the value of the required property.
         * 
         */
        public boolean isRequired() {
            return required;
        }

        /**
         * Sets the value of the required property.
         * 
         */
        public void setRequired(boolean value) {
            this.required = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="emailAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="firstName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="lastName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="pictureUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="active" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *         &lt;element name="admin" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id",
        "emailAddress",
        "firstName",
        "lastName",
        "pictureUrl",
        "active",
        "admin"
    })
    public static class User {

        protected long id;
        @XmlElement(required = true)
        protected String emailAddress;
        @XmlElement(required = true)
        protected String firstName;
        @XmlElement(required = true)
        protected String lastName;
        @XmlElement(required = true)
        protected String pictureUrl;
        protected boolean active;
        protected boolean admin;

        /**
         * Gets the value of the id property.
         * 
         */
        public long getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         */
        public void setId(long value) {
            this.id = value;
        }

        /**
         * Gets the value of the emailAddress property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEmailAddress() {
            return emailAddress;
        }

        /**
         * Sets the value of the emailAddress property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEmailAddress(String value) {
            this.emailAddress = value;
        }

        /**
         * Gets the value of the firstName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFirstName() {
            return firstName;
        }

        /**
         * Sets the value of the firstName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFirstName(String value) {
            this.firstName = value;
        }

        /**
         * Gets the value of the lastName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLastName() {
            return lastName;
        }

        /**
         * Sets the value of the lastName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLastName(String value) {
            this.lastName = value;
        }

        /**
         * Gets the value of the pictureUrl property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPictureUrl() {
            return pictureUrl;
        }

        /**
         * Sets the value of the pictureUrl property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPictureUrl(String value) {
            this.pictureUrl = value;
        }

        /**
         * Gets the value of the active property.
         * 
         */
        public boolean isActive() {
            return active;
        }

        /**
         * Sets the value of the active property.
         * 
         */
        public void setActive(boolean value) {
            this.active = value;
        }

        /**
         * Gets the value of the admin property.
         * 
         */
        public boolean isAdmin() {
            return admin;
        }

        /**
         * Sets the value of the admin property.
         * 
         */
        public void setAdmin(boolean value) {
            this.admin = value;
        }

    }

}
