//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.15 at 09:07:22 AM CST 
//


package org.sw.marketing.data.calendar;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="environment">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="componentId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="screenName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="serverName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="assets" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="contactName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="contactEmail" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="calendar" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="creationTimestamp" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="prettyUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="skinUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="skinSelector" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="event" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                             &lt;element name="startDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                             &lt;element name="endDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                             &lt;element name="startTime" type="{http://www.w3.org/2001/XMLSchema}time"/>
 *                             &lt;element name="endTime" type="{http://www.w3.org/2001/XMLSchema}time"/>
 *                             &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="locationOwned" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                             &lt;element name="location" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="locationAdditional" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="speaker" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="registrationLabel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="registrationUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="contactName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="contactPhone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="contactEmail" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="cost" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="tag" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                                       &lt;element name="label" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="fileName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="fileDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="eventRecurrence">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="recurring" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                                       &lt;element name="recurringMonthly" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                                       &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="limit" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="interval" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="by" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="monday" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                                       &lt;element name="tuesday" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                                       &lt;element name="wednesday" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                                       &lt;element name="thursday" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                                       &lt;element name="friday" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                                       &lt;element name="saturday" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                                       &lt;element name="sunday" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                                       &lt;element name="exact" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="categoryId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                             &lt;element name="parentId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                             &lt;element name="fkId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="role" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                             &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="fkCalendarId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="category" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                             &lt;element name="label" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="fkCalendarId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="messagePublicFormIntro" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="messagePublicFormClosing" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="deleted" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="message" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="subtype" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="label" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="questionId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="questionNumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="required" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="user">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="emailAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="firstName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="lastName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="pictureUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="active" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                   &lt;element name="admin" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "environment",
    "calendar",
    "message",
    "user"
})
@XmlRootElement(name = "data")
public class Data {

    @XmlElement(required = true)
    protected Data.Environment environment;
    protected List<Data.Calendar> calendar;
    protected List<Data.Message> message;
    @XmlElement(required = true)
    protected Data.User user;

    /**
     * Gets the value of the environment property.
     * 
     * @return
     *     possible object is
     *     {@link Data.Environment }
     *     
     */
    public Data.Environment getEnvironment() {
        return environment;
    }

    /**
     * Sets the value of the environment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Data.Environment }
     *     
     */
    public void setEnvironment(Data.Environment value) {
        this.environment = value;
    }

    /**
     * Gets the value of the calendar property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the calendar property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCalendar().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Data.Calendar }
     * 
     * 
     */
    public List<Data.Calendar> getCalendar() {
        if (calendar == null) {
            calendar = new ArrayList<Data.Calendar>();
        }
        return this.calendar;
    }

    /**
     * Gets the value of the message property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the message property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMessage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Data.Message }
     * 
     * 
     */
    public List<Data.Message> getMessage() {
        if (message == null) {
            message = new ArrayList<Data.Message>();
        }
        return this.message;
    }

    /**
     * Gets the value of the user property.
     * 
     * @return
     *     possible object is
     *     {@link Data.User }
     *     
     */
    public Data.User getUser() {
        return user;
    }

    /**
     * Sets the value of the user property.
     * 
     * @param value
     *     allowed object is
     *     {@link Data.User }
     *     
     */
    public void setUser(Data.User value) {
        this.user = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="creationTimestamp" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="prettyUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="skinUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="skinSelector" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="event" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                   &lt;element name="startDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *                   &lt;element name="endDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *                   &lt;element name="startTime" type="{http://www.w3.org/2001/XMLSchema}time"/>
     *                   &lt;element name="endTime" type="{http://www.w3.org/2001/XMLSchema}time"/>
     *                   &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="locationOwned" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="location" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="locationAdditional" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="speaker" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="registrationLabel" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="registrationUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="contactName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="contactPhone" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="contactEmail" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="cost" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="tag" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                             &lt;element name="label" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="fileName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="fileDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="eventRecurrence">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="recurring" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                             &lt;element name="recurringMonthly" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                             &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="limit" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                             &lt;element name="interval" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                             &lt;element name="by" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="monday" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                             &lt;element name="tuesday" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                             &lt;element name="wednesday" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                             &lt;element name="thursday" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                             &lt;element name="friday" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                             &lt;element name="saturday" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                             &lt;element name="sunday" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                             &lt;element name="exact" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="categoryId" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                   &lt;element name="parentId" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                   &lt;element name="fkId" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="role" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                   &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="fkCalendarId" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="category" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                   &lt;element name="label" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="fkCalendarId" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="messagePublicFormIntro" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="messagePublicFormClosing" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="deleted" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id",
        "creationTimestamp",
        "type",
        "title",
        "prettyUrl",
        "skinUrl",
        "skinSelector",
        "event",
        "role",
        "category",
        "messagePublicFormIntro",
        "messagePublicFormClosing",
        "deleted"
    })
    public static class Calendar {

        protected long id;
        @XmlElement(required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar creationTimestamp;
        @XmlElement(required = true)
        protected String type;
        @XmlElement(required = true)
        protected String title;
        @XmlElement(required = true)
        protected String prettyUrl;
        @XmlElement(required = true)
        protected String skinUrl;
        @XmlElement(required = true)
        protected String skinSelector;
        protected List<Data.Calendar.Event> event;
        protected List<Data.Calendar.Role> role;
        protected List<Data.Calendar.Category> category;
        @XmlElement(required = true)
        protected String messagePublicFormIntro;
        @XmlElement(required = true)
        protected String messagePublicFormClosing;
        protected boolean deleted;

        /**
         * Gets the value of the id property.
         * 
         */
        public long getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         */
        public void setId(long value) {
            this.id = value;
        }

        /**
         * Gets the value of the creationTimestamp property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getCreationTimestamp() {
            return creationTimestamp;
        }

        /**
         * Sets the value of the creationTimestamp property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setCreationTimestamp(XMLGregorianCalendar value) {
            this.creationTimestamp = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

        /**
         * Gets the value of the title property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTitle() {
            return title;
        }

        /**
         * Sets the value of the title property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTitle(String value) {
            this.title = value;
        }

        /**
         * Gets the value of the prettyUrl property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrettyUrl() {
            return prettyUrl;
        }

        /**
         * Sets the value of the prettyUrl property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrettyUrl(String value) {
            this.prettyUrl = value;
        }

        /**
         * Gets the value of the skinUrl property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSkinUrl() {
            return skinUrl;
        }

        /**
         * Sets the value of the skinUrl property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSkinUrl(String value) {
            this.skinUrl = value;
        }

        /**
         * Gets the value of the skinSelector property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSkinSelector() {
            return skinSelector;
        }

        /**
         * Sets the value of the skinSelector property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSkinSelector(String value) {
            this.skinSelector = value;
        }

        /**
         * Gets the value of the event property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the event property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEvent().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Data.Calendar.Event }
         * 
         * 
         */
        public List<Data.Calendar.Event> getEvent() {
            if (event == null) {
                event = new ArrayList<Data.Calendar.Event>();
            }
            return this.event;
        }

        /**
         * Gets the value of the role property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the role property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRole().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Data.Calendar.Role }
         * 
         * 
         */
        public List<Data.Calendar.Role> getRole() {
            if (role == null) {
                role = new ArrayList<Data.Calendar.Role>();
            }
            return this.role;
        }

        /**
         * Gets the value of the category property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the category property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCategory().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Data.Calendar.Category }
         * 
         * 
         */
        public List<Data.Calendar.Category> getCategory() {
            if (category == null) {
                category = new ArrayList<Data.Calendar.Category>();
            }
            return this.category;
        }

        /**
         * Gets the value of the messagePublicFormIntro property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMessagePublicFormIntro() {
            return messagePublicFormIntro;
        }

        /**
         * Sets the value of the messagePublicFormIntro property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMessagePublicFormIntro(String value) {
            this.messagePublicFormIntro = value;
        }

        /**
         * Gets the value of the messagePublicFormClosing property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMessagePublicFormClosing() {
            return messagePublicFormClosing;
        }

        /**
         * Sets the value of the messagePublicFormClosing property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMessagePublicFormClosing(String value) {
            this.messagePublicFormClosing = value;
        }

        /**
         * Gets the value of the deleted property.
         * 
         */
        public boolean isDeleted() {
            return deleted;
        }

        /**
         * Sets the value of the deleted property.
         * 
         */
        public void setDeleted(boolean value) {
            this.deleted = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *         &lt;element name="label" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="fkCalendarId" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "id",
            "label",
            "fkCalendarId"
        })
        public static class Category {

            protected long id;
            @XmlElement(required = true)
            protected String label;
            protected long fkCalendarId;

            /**
             * Gets the value of the id property.
             * 
             */
            public long getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             */
            public void setId(long value) {
                this.id = value;
            }

            /**
             * Gets the value of the label property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLabel() {
                return label;
            }

            /**
             * Sets the value of the label property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLabel(String value) {
                this.label = value;
            }

            /**
             * Gets the value of the fkCalendarId property.
             * 
             */
            public long getFkCalendarId() {
                return fkCalendarId;
            }

            /**
             * Sets the value of the fkCalendarId property.
             * 
             */
            public void setFkCalendarId(long value) {
                this.fkCalendarId = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *         &lt;element name="startDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
         *         &lt;element name="endDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
         *         &lt;element name="startTime" type="{http://www.w3.org/2001/XMLSchema}time"/>
         *         &lt;element name="endTime" type="{http://www.w3.org/2001/XMLSchema}time"/>
         *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="locationOwned" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="location" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="locationAdditional" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="speaker" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="registrationLabel" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="registrationUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="contactName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="contactPhone" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="contactEmail" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="cost" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="tag" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *                   &lt;element name="label" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="fileName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="fileDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="eventRecurrence">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="recurring" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *                   &lt;element name="recurringMonthly" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *                   &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="limit" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                   &lt;element name="interval" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                   &lt;element name="by" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="monday" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *                   &lt;element name="tuesday" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *                   &lt;element name="wednesday" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *                   &lt;element name="thursday" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *                   &lt;element name="friday" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *                   &lt;element name="saturday" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *                   &lt;element name="sunday" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *                   &lt;element name="exact" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="categoryId" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *         &lt;element name="parentId" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *         &lt;element name="fkId" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "id",
            "startDate",
            "endDate",
            "startTime",
            "endTime",
            "title",
            "locationOwned",
            "location",
            "locationAdditional",
            "description",
            "speaker",
            "registrationLabel",
            "registrationUrl",
            "contactName",
            "contactPhone",
            "contactEmail",
            "cost",
            "tag",
            "fileName",
            "fileDescription",
            "eventRecurrence",
            "categoryId",
            "parentId",
            "fkId"
        })
        public static class Event {

            protected long id;
            @XmlElement(required = true)
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar startDate;
            @XmlElement(required = true)
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar endDate;
            @XmlElement(required = true)
            @XmlSchemaType(name = "time")
            protected XMLGregorianCalendar startTime;
            @XmlElement(required = true)
            @XmlSchemaType(name = "time")
            protected XMLGregorianCalendar endTime;
            @XmlElement(required = true)
            protected String title;
            protected boolean locationOwned;
            @XmlElement(required = true)
            protected String location;
            @XmlElement(required = true)
            protected String locationAdditional;
            @XmlElement(required = true)
            protected String description;
            @XmlElement(required = true)
            protected String speaker;
            @XmlElement(required = true)
            protected String registrationLabel;
            @XmlElement(required = true)
            protected String registrationUrl;
            @XmlElement(required = true)
            protected String contactName;
            @XmlElement(required = true)
            protected String contactPhone;
            @XmlElement(required = true)
            protected String contactEmail;
            @XmlElement(required = true)
            protected String cost;
            protected List<Data.Calendar.Event.Tag> tag;
            @XmlElement(required = true)
            protected String fileName;
            @XmlElement(required = true)
            protected String fileDescription;
            @XmlElement(required = true)
            protected Data.Calendar.Event.EventRecurrence eventRecurrence;
            protected long categoryId;
            protected long parentId;
            protected long fkId;

            /**
             * Gets the value of the id property.
             * 
             */
            public long getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             */
            public void setId(long value) {
                this.id = value;
            }

            /**
             * Gets the value of the startDate property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getStartDate() {
                return startDate;
            }

            /**
             * Sets the value of the startDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setStartDate(XMLGregorianCalendar value) {
                this.startDate = value;
            }

            /**
             * Gets the value of the endDate property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getEndDate() {
                return endDate;
            }

            /**
             * Sets the value of the endDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setEndDate(XMLGregorianCalendar value) {
                this.endDate = value;
            }

            /**
             * Gets the value of the startTime property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getStartTime() {
                return startTime;
            }

            /**
             * Sets the value of the startTime property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setStartTime(XMLGregorianCalendar value) {
                this.startTime = value;
            }

            /**
             * Gets the value of the endTime property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getEndTime() {
                return endTime;
            }

            /**
             * Sets the value of the endTime property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setEndTime(XMLGregorianCalendar value) {
                this.endTime = value;
            }

            /**
             * Gets the value of the title property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTitle() {
                return title;
            }

            /**
             * Sets the value of the title property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTitle(String value) {
                this.title = value;
            }

            /**
             * Gets the value of the locationOwned property.
             * 
             */
            public boolean isLocationOwned() {
                return locationOwned;
            }

            /**
             * Sets the value of the locationOwned property.
             * 
             */
            public void setLocationOwned(boolean value) {
                this.locationOwned = value;
            }

            /**
             * Gets the value of the location property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLocation() {
                return location;
            }

            /**
             * Sets the value of the location property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLocation(String value) {
                this.location = value;
            }

            /**
             * Gets the value of the locationAdditional property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLocationAdditional() {
                return locationAdditional;
            }

            /**
             * Sets the value of the locationAdditional property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLocationAdditional(String value) {
                this.locationAdditional = value;
            }

            /**
             * Gets the value of the description property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDescription() {
                return description;
            }

            /**
             * Sets the value of the description property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDescription(String value) {
                this.description = value;
            }

            /**
             * Gets the value of the speaker property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSpeaker() {
                return speaker;
            }

            /**
             * Sets the value of the speaker property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSpeaker(String value) {
                this.speaker = value;
            }

            /**
             * Gets the value of the registrationLabel property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRegistrationLabel() {
                return registrationLabel;
            }

            /**
             * Sets the value of the registrationLabel property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRegistrationLabel(String value) {
                this.registrationLabel = value;
            }

            /**
             * Gets the value of the registrationUrl property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRegistrationUrl() {
                return registrationUrl;
            }

            /**
             * Sets the value of the registrationUrl property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRegistrationUrl(String value) {
                this.registrationUrl = value;
            }

            /**
             * Gets the value of the contactName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getContactName() {
                return contactName;
            }

            /**
             * Sets the value of the contactName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setContactName(String value) {
                this.contactName = value;
            }

            /**
             * Gets the value of the contactPhone property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getContactPhone() {
                return contactPhone;
            }

            /**
             * Sets the value of the contactPhone property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setContactPhone(String value) {
                this.contactPhone = value;
            }

            /**
             * Gets the value of the contactEmail property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getContactEmail() {
                return contactEmail;
            }

            /**
             * Sets the value of the contactEmail property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setContactEmail(String value) {
                this.contactEmail = value;
            }

            /**
             * Gets the value of the cost property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCost() {
                return cost;
            }

            /**
             * Sets the value of the cost property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCost(String value) {
                this.cost = value;
            }

            /**
             * Gets the value of the tag property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the tag property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getTag().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Data.Calendar.Event.Tag }
             * 
             * 
             */
            public List<Data.Calendar.Event.Tag> getTag() {
                if (tag == null) {
                    tag = new ArrayList<Data.Calendar.Event.Tag>();
                }
                return this.tag;
            }

            /**
             * Gets the value of the fileName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFileName() {
                return fileName;
            }

            /**
             * Sets the value of the fileName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFileName(String value) {
                this.fileName = value;
            }

            /**
             * Gets the value of the fileDescription property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFileDescription() {
                return fileDescription;
            }

            /**
             * Sets the value of the fileDescription property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFileDescription(String value) {
                this.fileDescription = value;
            }

            /**
             * Gets the value of the eventRecurrence property.
             * 
             * @return
             *     possible object is
             *     {@link Data.Calendar.Event.EventRecurrence }
             *     
             */
            public Data.Calendar.Event.EventRecurrence getEventRecurrence() {
                return eventRecurrence;
            }

            /**
             * Sets the value of the eventRecurrence property.
             * 
             * @param value
             *     allowed object is
             *     {@link Data.Calendar.Event.EventRecurrence }
             *     
             */
            public void setEventRecurrence(Data.Calendar.Event.EventRecurrence value) {
                this.eventRecurrence = value;
            }

            /**
             * Gets the value of the categoryId property.
             * 
             */
            public long getCategoryId() {
                return categoryId;
            }

            /**
             * Sets the value of the categoryId property.
             * 
             */
            public void setCategoryId(long value) {
                this.categoryId = value;
            }

            /**
             * Gets the value of the parentId property.
             * 
             */
            public long getParentId() {
                return parentId;
            }

            /**
             * Sets the value of the parentId property.
             * 
             */
            public void setParentId(long value) {
                this.parentId = value;
            }

            /**
             * Gets the value of the fkId property.
             * 
             */
            public long getFkId() {
                return fkId;
            }

            /**
             * Sets the value of the fkId property.
             * 
             */
            public void setFkId(long value) {
                this.fkId = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="recurring" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
             *         &lt;element name="recurringMonthly" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
             *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="limit" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *         &lt;element name="interval" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *         &lt;element name="by" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="monday" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
             *         &lt;element name="tuesday" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
             *         &lt;element name="wednesday" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
             *         &lt;element name="thursday" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
             *         &lt;element name="friday" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
             *         &lt;element name="saturday" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
             *         &lt;element name="sunday" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
             *         &lt;element name="exact" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "recurring",
                "recurringMonthly",
                "type",
                "limit",
                "interval",
                "by",
                "monday",
                "tuesday",
                "wednesday",
                "thursday",
                "friday",
                "saturday",
                "sunday",
                "exact"
            })
            public static class EventRecurrence {

                protected boolean recurring;
                protected boolean recurringMonthly;
                @XmlElement(required = true)
                protected String type;
                protected int limit;
                protected int interval;
                @XmlElement(required = true)
                protected String by;
                protected boolean monday;
                protected boolean tuesday;
                protected boolean wednesday;
                protected boolean thursday;
                protected boolean friday;
                protected boolean saturday;
                protected boolean sunday;
                protected boolean exact;

                /**
                 * Gets the value of the recurring property.
                 * 
                 */
                public boolean isRecurring() {
                    return recurring;
                }

                /**
                 * Sets the value of the recurring property.
                 * 
                 */
                public void setRecurring(boolean value) {
                    this.recurring = value;
                }

                /**
                 * Gets the value of the recurringMonthly property.
                 * 
                 */
                public boolean isRecurringMonthly() {
                    return recurringMonthly;
                }

                /**
                 * Sets the value of the recurringMonthly property.
                 * 
                 */
                public void setRecurringMonthly(boolean value) {
                    this.recurringMonthly = value;
                }

                /**
                 * Gets the value of the type property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getType() {
                    return type;
                }

                /**
                 * Sets the value of the type property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setType(String value) {
                    this.type = value;
                }

                /**
                 * Gets the value of the limit property.
                 * 
                 */
                public int getLimit() {
                    return limit;
                }

                /**
                 * Sets the value of the limit property.
                 * 
                 */
                public void setLimit(int value) {
                    this.limit = value;
                }

                /**
                 * Gets the value of the interval property.
                 * 
                 */
                public int getInterval() {
                    return interval;
                }

                /**
                 * Sets the value of the interval property.
                 * 
                 */
                public void setInterval(int value) {
                    this.interval = value;
                }

                /**
                 * Gets the value of the by property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getBy() {
                    return by;
                }

                /**
                 * Sets the value of the by property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setBy(String value) {
                    this.by = value;
                }

                /**
                 * Gets the value of the monday property.
                 * 
                 */
                public boolean isMonday() {
                    return monday;
                }

                /**
                 * Sets the value of the monday property.
                 * 
                 */
                public void setMonday(boolean value) {
                    this.monday = value;
                }

                /**
                 * Gets the value of the tuesday property.
                 * 
                 */
                public boolean isTuesday() {
                    return tuesday;
                }

                /**
                 * Sets the value of the tuesday property.
                 * 
                 */
                public void setTuesday(boolean value) {
                    this.tuesday = value;
                }

                /**
                 * Gets the value of the wednesday property.
                 * 
                 */
                public boolean isWednesday() {
                    return wednesday;
                }

                /**
                 * Sets the value of the wednesday property.
                 * 
                 */
                public void setWednesday(boolean value) {
                    this.wednesday = value;
                }

                /**
                 * Gets the value of the thursday property.
                 * 
                 */
                public boolean isThursday() {
                    return thursday;
                }

                /**
                 * Sets the value of the thursday property.
                 * 
                 */
                public void setThursday(boolean value) {
                    this.thursday = value;
                }

                /**
                 * Gets the value of the friday property.
                 * 
                 */
                public boolean isFriday() {
                    return friday;
                }

                /**
                 * Sets the value of the friday property.
                 * 
                 */
                public void setFriday(boolean value) {
                    this.friday = value;
                }

                /**
                 * Gets the value of the saturday property.
                 * 
                 */
                public boolean isSaturday() {
                    return saturday;
                }

                /**
                 * Sets the value of the saturday property.
                 * 
                 */
                public void setSaturday(boolean value) {
                    this.saturday = value;
                }

                /**
                 * Gets the value of the sunday property.
                 * 
                 */
                public boolean isSunday() {
                    return sunday;
                }

                /**
                 * Sets the value of the sunday property.
                 * 
                 */
                public void setSunday(boolean value) {
                    this.sunday = value;
                }

                /**
                 * Gets the value of the exact property.
                 * 
                 */
                public boolean isExact() {
                    return exact;
                }

                /**
                 * Sets the value of the exact property.
                 * 
                 */
                public void setExact(boolean value) {
                    this.exact = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
             *         &lt;element name="label" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "id",
                "label"
            })
            public static class Tag {

                protected long id;
                @XmlElement(required = true)
                protected String label;

                /**
                 * Gets the value of the id property.
                 * 
                 */
                public long getId() {
                    return id;
                }

                /**
                 * Sets the value of the id property.
                 * 
                 */
                public void setId(long value) {
                    this.id = value;
                }

                /**
                 * Gets the value of the label property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getLabel() {
                    return label;
                }

                /**
                 * Sets the value of the label property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setLabel(String value) {
                    this.label = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="fkCalendarId" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "id",
            "type",
            "email",
            "fkCalendarId"
        })
        public static class Role {

            protected long id;
            @XmlElement(required = true)
            protected String type;
            @XmlElement(required = true)
            protected String email;
            protected long fkCalendarId;

            /**
             * Gets the value of the id property.
             * 
             */
            public long getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             */
            public void setId(long value) {
                this.id = value;
            }

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setType(String value) {
                this.type = value;
            }

            /**
             * Gets the value of the email property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEmail() {
                return email;
            }

            /**
             * Sets the value of the email property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEmail(String value) {
                this.email = value;
            }

            /**
             * Gets the value of the fkCalendarId property.
             * 
             */
            public long getFkCalendarId() {
                return fkCalendarId;
            }

            /**
             * Sets the value of the fkCalendarId property.
             * 
             */
            public void setFkCalendarId(long value) {
                this.fkCalendarId = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="componentId" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="screenName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="serverName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="assets" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="contactName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="contactEmail" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "componentId",
        "screenName",
        "serverName",
        "assets",
        "contactName",
        "contactEmail"
    })
    public static class Environment {

        protected int componentId;
        @XmlElement(required = true)
        protected String screenName;
        @XmlElement(required = true)
        protected String serverName;
        @XmlElement(required = true)
        protected String assets;
        @XmlElement(required = true)
        protected String contactName;
        @XmlElement(required = true)
        protected String contactEmail;

        /**
         * Gets the value of the componentId property.
         * 
         */
        public int getComponentId() {
            return componentId;
        }

        /**
         * Sets the value of the componentId property.
         * 
         */
        public void setComponentId(int value) {
            this.componentId = value;
        }

        /**
         * Gets the value of the screenName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getScreenName() {
            return screenName;
        }

        /**
         * Sets the value of the screenName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setScreenName(String value) {
            this.screenName = value;
        }

        /**
         * Gets the value of the serverName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getServerName() {
            return serverName;
        }

        /**
         * Sets the value of the serverName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setServerName(String value) {
            this.serverName = value;
        }

        /**
         * Gets the value of the assets property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAssets() {
            return assets;
        }

        /**
         * Sets the value of the assets property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAssets(String value) {
            this.assets = value;
        }

        /**
         * Gets the value of the contactName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContactName() {
            return contactName;
        }

        /**
         * Sets the value of the contactName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContactName(String value) {
            this.contactName = value;
        }

        /**
         * Gets the value of the contactEmail property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContactEmail() {
            return contactEmail;
        }

        /**
         * Sets the value of the contactEmail property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContactEmail(String value) {
            this.contactEmail = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="subtype" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="label" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="questionId" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="questionNumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="required" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "type",
        "subtype",
        "label",
        "questionId",
        "questionNumber",
        "required"
    })
    public static class Message {

        @XmlElement(required = true)
        protected String type;
        @XmlElement(required = true)
        protected String subtype;
        @XmlElement(required = true)
        protected String label;
        protected long questionId;
        protected int questionNumber;
        protected boolean required;

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

        /**
         * Gets the value of the subtype property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSubtype() {
            return subtype;
        }

        /**
         * Sets the value of the subtype property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSubtype(String value) {
            this.subtype = value;
        }

        /**
         * Gets the value of the label property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLabel() {
            return label;
        }

        /**
         * Sets the value of the label property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLabel(String value) {
            this.label = value;
        }

        /**
         * Gets the value of the questionId property.
         * 
         */
        public long getQuestionId() {
            return questionId;
        }

        /**
         * Sets the value of the questionId property.
         * 
         */
        public void setQuestionId(long value) {
            this.questionId = value;
        }

        /**
         * Gets the value of the questionNumber property.
         * 
         */
        public int getQuestionNumber() {
            return questionNumber;
        }

        /**
         * Sets the value of the questionNumber property.
         * 
         */
        public void setQuestionNumber(int value) {
            this.questionNumber = value;
        }

        /**
         * Gets the value of the required property.
         * 
         */
        public boolean isRequired() {
            return required;
        }

        /**
         * Sets the value of the required property.
         * 
         */
        public void setRequired(boolean value) {
            this.required = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="emailAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="firstName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="lastName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="pictureUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="active" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *         &lt;element name="admin" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id",
        "emailAddress",
        "firstName",
        "lastName",
        "pictureUrl",
        "active",
        "admin"
    })
    public static class User {

        protected long id;
        @XmlElement(required = true)
        protected String emailAddress;
        @XmlElement(required = true)
        protected String firstName;
        @XmlElement(required = true)
        protected String lastName;
        @XmlElement(required = true)
        protected String pictureUrl;
        protected boolean active;
        protected boolean admin;

        /**
         * Gets the value of the id property.
         * 
         */
        public long getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         */
        public void setId(long value) {
            this.id = value;
        }

        /**
         * Gets the value of the emailAddress property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEmailAddress() {
            return emailAddress;
        }

        /**
         * Sets the value of the emailAddress property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEmailAddress(String value) {
            this.emailAddress = value;
        }

        /**
         * Gets the value of the firstName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFirstName() {
            return firstName;
        }

        /**
         * Sets the value of the firstName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFirstName(String value) {
            this.firstName = value;
        }

        /**
         * Gets the value of the lastName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLastName() {
            return lastName;
        }

        /**
         * Sets the value of the lastName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLastName(String value) {
            this.lastName = value;
        }

        /**
         * Gets the value of the pictureUrl property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPictureUrl() {
            return pictureUrl;
        }

        /**
         * Sets the value of the pictureUrl property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPictureUrl(String value) {
            this.pictureUrl = value;
        }

        /**
         * Gets the value of the active property.
         * 
         */
        public boolean isActive() {
            return active;
        }

        /**
         * Sets the value of the active property.
         * 
         */
        public void setActive(boolean value) {
            this.active = value;
        }

        /**
         * Gets the value of the admin property.
         * 
         */
        public boolean isAdmin() {
            return admin;
        }

        /**
         * Sets the value of the admin property.
         * 
         */
        public void setAdmin(boolean value) {
            this.admin = value;
        }

    }

}
