//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.03 at 09:33:01 AM CST 
//


package org.sw.marketing.data.form;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="environment">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="componentId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="screenName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="serverName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="assets" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="contactName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="contactEmail" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="form" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="creationTimestamp" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;element name="startDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;element name="endDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="prettyUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="maxSubmissions" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="submissionCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="returnUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="skinUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="skinSelector" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="question" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                             &lt;element name="number" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="header" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="label" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="page" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="defaultAnswer" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="filter" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="maxCharacterLimit" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="maxWordLimit" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="required" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                             &lt;element name="possibleAnswer" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                                       &lt;element name="label" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="fkId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="currentPage" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="lastPage" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="score" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="messagePublicFormIntro" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="messagePublicFormClosing" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="messageEnded" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="messageMaxSubmitted" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="messageNotStarted" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="messageOneSubmission" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="messageThankYou" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="started" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                   &lt;element name="ended" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                   &lt;element name="deleted" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="possibleAnswer" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="label" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="score" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="begin" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="end" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="summary" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="submission" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="ip" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="page" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="userId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="answer" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="questionId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                             &lt;element name="multipleChoice" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                             &lt;element name="answerValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="answerLabel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="message" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="subtype" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="label" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="questionId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="questionNumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="required" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="user">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="emailAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="firstName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="lastName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="pictureUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="active" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                   &lt;element name="admin" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="analytics">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="startDateStr" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="endDateStr" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "environment",
    "form",
    "possibleAnswer",
    "score",
    "submission",
    "message",
    "user",
    "analytics"
})
@XmlRootElement(name = "data")
public class Data {

    @XmlElement(required = true)
    protected Data.Environment environment;
    protected List<Data.Form> form;
    protected List<Data.PossibleAnswer> possibleAnswer;
    protected List<Data.Score> score;
    protected List<Data.Submission> submission;
    protected List<Data.Message> message;
    @XmlElement(required = true)
    protected Data.User user;
    @XmlElement(required = true)
    protected Data.Analytics analytics;

    /**
     * Gets the value of the environment property.
     * 
     * @return
     *     possible object is
     *     {@link Data.Environment }
     *     
     */
    public Data.Environment getEnvironment() {
        return environment;
    }

    /**
     * Sets the value of the environment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Data.Environment }
     *     
     */
    public void setEnvironment(Data.Environment value) {
        this.environment = value;
    }

    /**
     * Gets the value of the form property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the form property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getForm().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Data.Form }
     * 
     * 
     */
    public List<Data.Form> getForm() {
        if (form == null) {
            form = new ArrayList<Data.Form>();
        }
        return this.form;
    }

    /**
     * Gets the value of the possibleAnswer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the possibleAnswer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPossibleAnswer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Data.PossibleAnswer }
     * 
     * 
     */
    public List<Data.PossibleAnswer> getPossibleAnswer() {
        if (possibleAnswer == null) {
            possibleAnswer = new ArrayList<Data.PossibleAnswer>();
        }
        return this.possibleAnswer;
    }

    /**
     * Gets the value of the score property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the score property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getScore().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Data.Score }
     * 
     * 
     */
    public List<Data.Score> getScore() {
        if (score == null) {
            score = new ArrayList<Data.Score>();
        }
        return this.score;
    }

    /**
     * Gets the value of the submission property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the submission property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubmission().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Data.Submission }
     * 
     * 
     */
    public List<Data.Submission> getSubmission() {
        if (submission == null) {
            submission = new ArrayList<Data.Submission>();
        }
        return this.submission;
    }

    /**
     * Gets the value of the message property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the message property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMessage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Data.Message }
     * 
     * 
     */
    public List<Data.Message> getMessage() {
        if (message == null) {
            message = new ArrayList<Data.Message>();
        }
        return this.message;
    }

    /**
     * Gets the value of the user property.
     * 
     * @return
     *     possible object is
     *     {@link Data.User }
     *     
     */
    public Data.User getUser() {
        return user;
    }

    /**
     * Sets the value of the user property.
     * 
     * @param value
     *     allowed object is
     *     {@link Data.User }
     *     
     */
    public void setUser(Data.User value) {
        this.user = value;
    }

    /**
     * Gets the value of the analytics property.
     * 
     * @return
     *     possible object is
     *     {@link Data.Analytics }
     *     
     */
    public Data.Analytics getAnalytics() {
        return analytics;
    }

    /**
     * Sets the value of the analytics property.
     * 
     * @param value
     *     allowed object is
     *     {@link Data.Analytics }
     *     
     */
    public void setAnalytics(Data.Analytics value) {
        this.analytics = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="startDateStr" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="endDateStr" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "startDateStr",
        "endDateStr"
    })
    public static class Analytics {

        @XmlElement(required = true)
        protected String startDateStr;
        @XmlElement(required = true)
        protected String endDateStr;

        /**
         * Gets the value of the startDateStr property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStartDateStr() {
            return startDateStr;
        }

        /**
         * Sets the value of the startDateStr property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStartDateStr(String value) {
            this.startDateStr = value;
        }

        /**
         * Gets the value of the endDateStr property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEndDateStr() {
            return endDateStr;
        }

        /**
         * Sets the value of the endDateStr property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEndDateStr(String value) {
            this.endDateStr = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="componentId" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="screenName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="serverName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="assets" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="contactName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="contactEmail" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "componentId",
        "screenName",
        "serverName",
        "assets",
        "contactName",
        "contactEmail"
    })
    public static class Environment {

        protected int componentId;
        @XmlElement(required = true)
        protected String screenName;
        @XmlElement(required = true)
        protected String serverName;
        @XmlElement(required = true)
        protected String assets;
        @XmlElement(required = true)
        protected String contactName;
        @XmlElement(required = true)
        protected String contactEmail;

        /**
         * Gets the value of the componentId property.
         * 
         */
        public int getComponentId() {
            return componentId;
        }

        /**
         * Sets the value of the componentId property.
         * 
         */
        public void setComponentId(int value) {
            this.componentId = value;
        }

        /**
         * Gets the value of the screenName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getScreenName() {
            return screenName;
        }

        /**
         * Sets the value of the screenName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setScreenName(String value) {
            this.screenName = value;
        }

        /**
         * Gets the value of the serverName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getServerName() {
            return serverName;
        }

        /**
         * Sets the value of the serverName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setServerName(String value) {
            this.serverName = value;
        }

        /**
         * Gets the value of the assets property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAssets() {
            return assets;
        }

        /**
         * Sets the value of the assets property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAssets(String value) {
            this.assets = value;
        }

        /**
         * Gets the value of the contactName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContactName() {
            return contactName;
        }

        /**
         * Sets the value of the contactName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContactName(String value) {
            this.contactName = value;
        }

        /**
         * Gets the value of the contactEmail property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContactEmail() {
            return contactEmail;
        }

        /**
         * Sets the value of the contactEmail property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContactEmail(String value) {
            this.contactEmail = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="creationTimestamp" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *         &lt;element name="startDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *         &lt;element name="endDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="prettyUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="maxSubmissions" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="submissionCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="returnUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="skinUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="skinSelector" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="question" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                   &lt;element name="number" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="header" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="label" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="page" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="defaultAnswer" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="filter" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="maxCharacterLimit" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="maxWordLimit" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="required" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="possibleAnswer" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                             &lt;element name="label" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="fkId" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="currentPage" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="lastPage" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="score" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="messagePublicFormIntro" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="messagePublicFormClosing" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="messageEnded" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="messageMaxSubmitted" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="messageNotStarted" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="messageOneSubmission" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="messageThankYou" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="started" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *         &lt;element name="ended" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *         &lt;element name="deleted" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id",
        "creationTimestamp",
        "startDate",
        "endDate",
        "type",
        "status",
        "title",
        "prettyUrl",
        "maxSubmissions",
        "submissionCount",
        "returnUrl",
        "skinUrl",
        "skinSelector",
        "question",
        "currentPage",
        "lastPage",
        "score",
        "messagePublicFormIntro",
        "messagePublicFormClosing",
        "messageEnded",
        "messageMaxSubmitted",
        "messageNotStarted",
        "messageOneSubmission",
        "messageThankYou",
        "started",
        "ended",
        "deleted"
    })
    public static class Form {

        protected long id;
        @XmlElement(required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar creationTimestamp;
        @XmlElement(required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar startDate;
        @XmlElement(required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar endDate;
        @XmlElement(required = true)
        protected String type;
        @XmlElement(required = true)
        protected String status;
        @XmlElement(required = true)
        protected String title;
        @XmlElement(required = true)
        protected String prettyUrl;
        protected int maxSubmissions;
        protected int submissionCount;
        @XmlElement(required = true)
        protected String returnUrl;
        @XmlElement(required = true)
        protected String skinUrl;
        @XmlElement(required = true)
        protected String skinSelector;
        protected List<Data.Form.Question> question;
        protected int currentPage;
        protected int lastPage;
        protected int score;
        @XmlElement(required = true)
        protected String messagePublicFormIntro;
        @XmlElement(required = true)
        protected String messagePublicFormClosing;
        @XmlElement(required = true)
        protected String messageEnded;
        @XmlElement(required = true)
        protected String messageMaxSubmitted;
        @XmlElement(required = true)
        protected String messageNotStarted;
        @XmlElement(required = true)
        protected String messageOneSubmission;
        @XmlElement(required = true)
        protected String messageThankYou;
        protected boolean started;
        protected boolean ended;
        protected boolean deleted;

        /**
         * Gets the value of the id property.
         * 
         */
        public long getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         */
        public void setId(long value) {
            this.id = value;
        }

        /**
         * Gets the value of the creationTimestamp property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getCreationTimestamp() {
            return creationTimestamp;
        }

        /**
         * Sets the value of the creationTimestamp property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setCreationTimestamp(XMLGregorianCalendar value) {
            this.creationTimestamp = value;
        }

        /**
         * Gets the value of the startDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getStartDate() {
            return startDate;
        }

        /**
         * Sets the value of the startDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setStartDate(XMLGregorianCalendar value) {
            this.startDate = value;
        }

        /**
         * Gets the value of the endDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getEndDate() {
            return endDate;
        }

        /**
         * Sets the value of the endDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setEndDate(XMLGregorianCalendar value) {
            this.endDate = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

        /**
         * Gets the value of the status property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStatus() {
            return status;
        }

        /**
         * Sets the value of the status property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStatus(String value) {
            this.status = value;
        }

        /**
         * Gets the value of the title property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTitle() {
            return title;
        }

        /**
         * Sets the value of the title property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTitle(String value) {
            this.title = value;
        }

        /**
         * Gets the value of the prettyUrl property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrettyUrl() {
            return prettyUrl;
        }

        /**
         * Sets the value of the prettyUrl property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrettyUrl(String value) {
            this.prettyUrl = value;
        }

        /**
         * Gets the value of the maxSubmissions property.
         * 
         */
        public int getMaxSubmissions() {
            return maxSubmissions;
        }

        /**
         * Sets the value of the maxSubmissions property.
         * 
         */
        public void setMaxSubmissions(int value) {
            this.maxSubmissions = value;
        }

        /**
         * Gets the value of the submissionCount property.
         * 
         */
        public int getSubmissionCount() {
            return submissionCount;
        }

        /**
         * Sets the value of the submissionCount property.
         * 
         */
        public void setSubmissionCount(int value) {
            this.submissionCount = value;
        }

        /**
         * Gets the value of the returnUrl property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReturnUrl() {
            return returnUrl;
        }

        /**
         * Sets the value of the returnUrl property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReturnUrl(String value) {
            this.returnUrl = value;
        }

        /**
         * Gets the value of the skinUrl property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSkinUrl() {
            return skinUrl;
        }

        /**
         * Sets the value of the skinUrl property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSkinUrl(String value) {
            this.skinUrl = value;
        }

        /**
         * Gets the value of the skinSelector property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSkinSelector() {
            return skinSelector;
        }

        /**
         * Sets the value of the skinSelector property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSkinSelector(String value) {
            this.skinSelector = value;
        }

        /**
         * Gets the value of the question property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the question property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getQuestion().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Data.Form.Question }
         * 
         * 
         */
        public List<Data.Form.Question> getQuestion() {
            if (question == null) {
                question = new ArrayList<Data.Form.Question>();
            }
            return this.question;
        }

        /**
         * Gets the value of the currentPage property.
         * 
         */
        public int getCurrentPage() {
            return currentPage;
        }

        /**
         * Sets the value of the currentPage property.
         * 
         */
        public void setCurrentPage(int value) {
            this.currentPage = value;
        }

        /**
         * Gets the value of the lastPage property.
         * 
         */
        public int getLastPage() {
            return lastPage;
        }

        /**
         * Sets the value of the lastPage property.
         * 
         */
        public void setLastPage(int value) {
            this.lastPage = value;
        }

        /**
         * Gets the value of the score property.
         * 
         */
        public int getScore() {
            return score;
        }

        /**
         * Sets the value of the score property.
         * 
         */
        public void setScore(int value) {
            this.score = value;
        }

        /**
         * Gets the value of the messagePublicFormIntro property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMessagePublicFormIntro() {
            return messagePublicFormIntro;
        }

        /**
         * Sets the value of the messagePublicFormIntro property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMessagePublicFormIntro(String value) {
            this.messagePublicFormIntro = value;
        }

        /**
         * Gets the value of the messagePublicFormClosing property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMessagePublicFormClosing() {
            return messagePublicFormClosing;
        }

        /**
         * Sets the value of the messagePublicFormClosing property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMessagePublicFormClosing(String value) {
            this.messagePublicFormClosing = value;
        }

        /**
         * Gets the value of the messageEnded property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMessageEnded() {
            return messageEnded;
        }

        /**
         * Sets the value of the messageEnded property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMessageEnded(String value) {
            this.messageEnded = value;
        }

        /**
         * Gets the value of the messageMaxSubmitted property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMessageMaxSubmitted() {
            return messageMaxSubmitted;
        }

        /**
         * Sets the value of the messageMaxSubmitted property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMessageMaxSubmitted(String value) {
            this.messageMaxSubmitted = value;
        }

        /**
         * Gets the value of the messageNotStarted property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMessageNotStarted() {
            return messageNotStarted;
        }

        /**
         * Sets the value of the messageNotStarted property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMessageNotStarted(String value) {
            this.messageNotStarted = value;
        }

        /**
         * Gets the value of the messageOneSubmission property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMessageOneSubmission() {
            return messageOneSubmission;
        }

        /**
         * Sets the value of the messageOneSubmission property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMessageOneSubmission(String value) {
            this.messageOneSubmission = value;
        }

        /**
         * Gets the value of the messageThankYou property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMessageThankYou() {
            return messageThankYou;
        }

        /**
         * Sets the value of the messageThankYou property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMessageThankYou(String value) {
            this.messageThankYou = value;
        }

        /**
         * Gets the value of the started property.
         * 
         */
        public boolean isStarted() {
            return started;
        }

        /**
         * Sets the value of the started property.
         * 
         */
        public void setStarted(boolean value) {
            this.started = value;
        }

        /**
         * Gets the value of the ended property.
         * 
         */
        public boolean isEnded() {
            return ended;
        }

        /**
         * Sets the value of the ended property.
         * 
         */
        public void setEnded(boolean value) {
            this.ended = value;
        }

        /**
         * Gets the value of the deleted property.
         * 
         */
        public boolean isDeleted() {
            return deleted;
        }

        /**
         * Sets the value of the deleted property.
         * 
         */
        public void setDeleted(boolean value) {
            this.deleted = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *         &lt;element name="number" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="header" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="label" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="page" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="defaultAnswer" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="filter" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="maxCharacterLimit" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="maxWordLimit" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="required" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="possibleAnswer" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *                   &lt;element name="label" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="fkId" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "id",
            "number",
            "type",
            "header",
            "label",
            "page",
            "defaultAnswer",
            "filter",
            "maxCharacterLimit",
            "maxWordLimit",
            "required",
            "possibleAnswer",
            "fkId"
        })
        public static class Question {

            protected long id;
            protected int number;
            @XmlElement(required = true)
            protected String type;
            @XmlElement(required = true)
            protected String header;
            @XmlElement(required = true)
            protected String label;
            protected int page;
            @XmlElement(required = true)
            protected String defaultAnswer;
            @XmlElement(required = true)
            protected String filter;
            protected int maxCharacterLimit;
            protected int maxWordLimit;
            protected boolean required;
            protected List<Data.Form.Question.PossibleAnswer> possibleAnswer;
            protected int fkId;

            /**
             * Gets the value of the id property.
             * 
             */
            public long getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             */
            public void setId(long value) {
                this.id = value;
            }

            /**
             * Gets the value of the number property.
             * 
             */
            public int getNumber() {
                return number;
            }

            /**
             * Sets the value of the number property.
             * 
             */
            public void setNumber(int value) {
                this.number = value;
            }

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setType(String value) {
                this.type = value;
            }

            /**
             * Gets the value of the header property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getHeader() {
                return header;
            }

            /**
             * Sets the value of the header property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setHeader(String value) {
                this.header = value;
            }

            /**
             * Gets the value of the label property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLabel() {
                return label;
            }

            /**
             * Sets the value of the label property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLabel(String value) {
                this.label = value;
            }

            /**
             * Gets the value of the page property.
             * 
             */
            public int getPage() {
                return page;
            }

            /**
             * Sets the value of the page property.
             * 
             */
            public void setPage(int value) {
                this.page = value;
            }

            /**
             * Gets the value of the defaultAnswer property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDefaultAnswer() {
                return defaultAnswer;
            }

            /**
             * Sets the value of the defaultAnswer property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDefaultAnswer(String value) {
                this.defaultAnswer = value;
            }

            /**
             * Gets the value of the filter property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFilter() {
                return filter;
            }

            /**
             * Sets the value of the filter property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFilter(String value) {
                this.filter = value;
            }

            /**
             * Gets the value of the maxCharacterLimit property.
             * 
             */
            public int getMaxCharacterLimit() {
                return maxCharacterLimit;
            }

            /**
             * Sets the value of the maxCharacterLimit property.
             * 
             */
            public void setMaxCharacterLimit(int value) {
                this.maxCharacterLimit = value;
            }

            /**
             * Gets the value of the maxWordLimit property.
             * 
             */
            public int getMaxWordLimit() {
                return maxWordLimit;
            }

            /**
             * Sets the value of the maxWordLimit property.
             * 
             */
            public void setMaxWordLimit(int value) {
                this.maxWordLimit = value;
            }

            /**
             * Gets the value of the required property.
             * 
             */
            public boolean isRequired() {
                return required;
            }

            /**
             * Sets the value of the required property.
             * 
             */
            public void setRequired(boolean value) {
                this.required = value;
            }

            /**
             * Gets the value of the possibleAnswer property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the possibleAnswer property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getPossibleAnswer().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Data.Form.Question.PossibleAnswer }
             * 
             * 
             */
            public List<Data.Form.Question.PossibleAnswer> getPossibleAnswer() {
                if (possibleAnswer == null) {
                    possibleAnswer = new ArrayList<Data.Form.Question.PossibleAnswer>();
                }
                return this.possibleAnswer;
            }

            /**
             * Gets the value of the fkId property.
             * 
             */
            public int getFkId() {
                return fkId;
            }

            /**
             * Sets the value of the fkId property.
             * 
             */
            public void setFkId(int value) {
                this.fkId = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
             *         &lt;element name="label" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "id",
                "label",
                "value"
            })
            public static class PossibleAnswer {

                protected long id;
                @XmlElement(required = true)
                protected String label;
                protected int value;

                /**
                 * Gets the value of the id property.
                 * 
                 */
                public long getId() {
                    return id;
                }

                /**
                 * Sets the value of the id property.
                 * 
                 */
                public void setId(long value) {
                    this.id = value;
                }

                /**
                 * Gets the value of the label property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getLabel() {
                    return label;
                }

                /**
                 * Sets the value of the label property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setLabel(String value) {
                    this.label = value;
                }

                /**
                 * Gets the value of the value property.
                 * 
                 */
                public int getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 */
                public void setValue(int value) {
                    this.value = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="subtype" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="label" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="questionId" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="questionNumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="required" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "type",
        "subtype",
        "label",
        "questionId",
        "questionNumber",
        "required"
    })
    public static class Message {

        @XmlElement(required = true)
        protected String type;
        @XmlElement(required = true)
        protected String subtype;
        @XmlElement(required = true)
        protected String label;
        protected long questionId;
        protected int questionNumber;
        protected boolean required;

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

        /**
         * Gets the value of the subtype property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSubtype() {
            return subtype;
        }

        /**
         * Sets the value of the subtype property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSubtype(String value) {
            this.subtype = value;
        }

        /**
         * Gets the value of the label property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLabel() {
            return label;
        }

        /**
         * Sets the value of the label property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLabel(String value) {
            this.label = value;
        }

        /**
         * Gets the value of the questionId property.
         * 
         */
        public long getQuestionId() {
            return questionId;
        }

        /**
         * Sets the value of the questionId property.
         * 
         */
        public void setQuestionId(long value) {
            this.questionId = value;
        }

        /**
         * Gets the value of the questionNumber property.
         * 
         */
        public int getQuestionNumber() {
            return questionNumber;
        }

        /**
         * Sets the value of the questionNumber property.
         * 
         */
        public void setQuestionNumber(int value) {
            this.questionNumber = value;
        }

        /**
         * Gets the value of the required property.
         * 
         */
        public boolean isRequired() {
            return required;
        }

        /**
         * Sets the value of the required property.
         * 
         */
        public void setRequired(boolean value) {
            this.required = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="label" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id",
        "label",
        "value"
    })
    public static class PossibleAnswer {

        protected long id;
        @XmlElement(required = true)
        protected String label;
        protected int value;

        /**
         * Gets the value of the id property.
         * 
         */
        public long getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         */
        public void setId(long value) {
            this.id = value;
        }

        /**
         * Gets the value of the label property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLabel() {
            return label;
        }

        /**
         * Sets the value of the label property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLabel(String value) {
            this.label = value;
        }

        /**
         * Gets the value of the value property.
         * 
         */
        public int getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         */
        public void setValue(int value) {
            this.value = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="begin" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="end" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="summary" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id",
        "begin",
        "end",
        "title",
        "summary"
    })
    public static class Score {

        protected long id;
        protected int begin;
        protected int end;
        @XmlElement(required = true)
        protected String title;
        @XmlElement(required = true)
        protected String summary;

        /**
         * Gets the value of the id property.
         * 
         */
        public long getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         */
        public void setId(long value) {
            this.id = value;
        }

        /**
         * Gets the value of the begin property.
         * 
         */
        public int getBegin() {
            return begin;
        }

        /**
         * Sets the value of the begin property.
         * 
         */
        public void setBegin(int value) {
            this.begin = value;
        }

        /**
         * Gets the value of the end property.
         * 
         */
        public int getEnd() {
            return end;
        }

        /**
         * Sets the value of the end property.
         * 
         */
        public void setEnd(int value) {
            this.end = value;
        }

        /**
         * Gets the value of the title property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTitle() {
            return title;
        }

        /**
         * Sets the value of the title property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTitle(String value) {
            this.title = value;
        }

        /**
         * Gets the value of the summary property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSummary() {
            return summary;
        }

        /**
         * Sets the value of the summary property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSummary(String value) {
            this.summary = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="ip" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="page" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="userId" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="answer" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="questionId" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                   &lt;element name="multipleChoice" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="answerValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="answerLabel" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id",
        "ip",
        "page",
        "userId",
        "answer"
    })
    public static class Submission {

        protected long id;
        @XmlElement(required = true)
        protected String ip;
        protected int page;
        protected long userId;
        protected List<Data.Submission.Answer> answer;

        /**
         * Gets the value of the id property.
         * 
         */
        public long getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         */
        public void setId(long value) {
            this.id = value;
        }

        /**
         * Gets the value of the ip property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIp() {
            return ip;
        }

        /**
         * Sets the value of the ip property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIp(String value) {
            this.ip = value;
        }

        /**
         * Gets the value of the page property.
         * 
         */
        public int getPage() {
            return page;
        }

        /**
         * Sets the value of the page property.
         * 
         */
        public void setPage(int value) {
            this.page = value;
        }

        /**
         * Gets the value of the userId property.
         * 
         */
        public long getUserId() {
            return userId;
        }

        /**
         * Sets the value of the userId property.
         * 
         */
        public void setUserId(long value) {
            this.userId = value;
        }

        /**
         * Gets the value of the answer property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the answer property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAnswer().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Data.Submission.Answer }
         * 
         * 
         */
        public List<Data.Submission.Answer> getAnswer() {
            if (answer == null) {
                answer = new ArrayList<Data.Submission.Answer>();
            }
            return this.answer;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="questionId" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *         &lt;element name="multipleChoice" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="answerValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="answerLabel" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "questionId",
            "multipleChoice",
            "answerValue",
            "answerLabel"
        })
        public static class Answer {

            protected long questionId;
            protected boolean multipleChoice;
            @XmlElement(required = true)
            protected String answerValue;
            @XmlElement(required = true)
            protected String answerLabel;

            /**
             * Gets the value of the questionId property.
             * 
             */
            public long getQuestionId() {
                return questionId;
            }

            /**
             * Sets the value of the questionId property.
             * 
             */
            public void setQuestionId(long value) {
                this.questionId = value;
            }

            /**
             * Gets the value of the multipleChoice property.
             * 
             */
            public boolean isMultipleChoice() {
                return multipleChoice;
            }

            /**
             * Sets the value of the multipleChoice property.
             * 
             */
            public void setMultipleChoice(boolean value) {
                this.multipleChoice = value;
            }

            /**
             * Gets the value of the answerValue property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAnswerValue() {
                return answerValue;
            }

            /**
             * Sets the value of the answerValue property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAnswerValue(String value) {
                this.answerValue = value;
            }

            /**
             * Gets the value of the answerLabel property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAnswerLabel() {
                return answerLabel;
            }

            /**
             * Sets the value of the answerLabel property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAnswerLabel(String value) {
                this.answerLabel = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="emailAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="firstName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="lastName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="pictureUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="active" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *         &lt;element name="admin" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id",
        "emailAddress",
        "firstName",
        "lastName",
        "pictureUrl",
        "active",
        "admin"
    })
    public static class User {

        protected long id;
        @XmlElement(required = true)
        protected String emailAddress;
        @XmlElement(required = true)
        protected String firstName;
        @XmlElement(required = true)
        protected String lastName;
        @XmlElement(required = true)
        protected String pictureUrl;
        protected boolean active;
        protected boolean admin;

        /**
         * Gets the value of the id property.
         * 
         */
        public long getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         */
        public void setId(long value) {
            this.id = value;
        }

        /**
         * Gets the value of the emailAddress property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEmailAddress() {
            return emailAddress;
        }

        /**
         * Sets the value of the emailAddress property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEmailAddress(String value) {
            this.emailAddress = value;
        }

        /**
         * Gets the value of the firstName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFirstName() {
            return firstName;
        }

        /**
         * Sets the value of the firstName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFirstName(String value) {
            this.firstName = value;
        }

        /**
         * Gets the value of the lastName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLastName() {
            return lastName;
        }

        /**
         * Sets the value of the lastName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLastName(String value) {
            this.lastName = value;
        }

        /**
         * Gets the value of the pictureUrl property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPictureUrl() {
            return pictureUrl;
        }

        /**
         * Sets the value of the pictureUrl property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPictureUrl(String value) {
            this.pictureUrl = value;
        }

        /**
         * Gets the value of the active property.
         * 
         */
        public boolean isActive() {
            return active;
        }

        /**
         * Sets the value of the active property.
         * 
         */
        public void setActive(boolean value) {
            this.active = value;
        }

        /**
         * Gets the value of the admin property.
         * 
         */
        public boolean isAdmin() {
            return admin;
        }

        /**
         * Sets the value of the admin property.
         * 
         */
        public void setAdmin(boolean value) {
            this.admin = value;
        }

    }

}
