//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.22 at 02:46:08 PM CST 
//


package org.sw.marketing.data.form;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.sw.marketing.data.form package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.sw.marketing.data.form
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Data }
     * 
     */
    public Data createData() {
        return new Data();
    }

    /**
     * Create an instance of {@link Data.Submission }
     * 
     */
    public Data.Submission createDataSubmission() {
        return new Data.Submission();
    }

    /**
     * Create an instance of {@link Data.Form }
     * 
     */
    public Data.Form createDataForm() {
        return new Data.Form();
    }

    /**
     * Create an instance of {@link Data.Form.Question }
     * 
     */
    public Data.Form.Question createDataFormQuestion() {
        return new Data.Form.Question();
    }

    /**
     * Create an instance of {@link Data.Environment }
     * 
     */
    public Data.Environment createDataEnvironment() {
        return new Data.Environment();
    }

    /**
     * Create an instance of {@link Data.PossibleAnswer }
     * 
     */
    public Data.PossibleAnswer createDataPossibleAnswer() {
        return new Data.PossibleAnswer();
    }

    /**
     * Create an instance of {@link Data.Message }
     * 
     */
    public Data.Message createDataMessage() {
        return new Data.Message();
    }

    /**
     * Create an instance of {@link Data.User }
     * 
     */
    public Data.User createDataUser() {
        return new Data.User();
    }

    /**
     * Create an instance of {@link Data.Analytics }
     * 
     */
    public Data.Analytics createDataAnalytics() {
        return new Data.Analytics();
    }

    /**
     * Create an instance of {@link Data.Submission.Answer }
     * 
     */
    public Data.Submission.Answer createDataSubmissionAnswer() {
        return new Data.Submission.Answer();
    }

    /**
     * Create an instance of {@link Data.Form.Question.PossibleAnswer }
     * 
     */
    public Data.Form.Question.PossibleAnswer createDataFormQuestionPossibleAnswer() {
        return new Data.Form.Question.PossibleAnswer();
    }

}
