//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.28 at 08:00:36 PM CST 
//


package org.sw.marketing.data.skin;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}environment"/>
 *         &lt;element name="skin" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="creationTimestamp" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="editable" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                   &lt;element name="skinUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="skinSelector" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="skinCssOverrides" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="role" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                             &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="fkCalendarId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="deleted" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{}message" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}user"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "environment",
    "skin",
    "message",
    "user"
})
@XmlRootElement(name = "data")
public class Data {

    @XmlElement(required = true)
    protected Environment environment;
    protected List<Data.Skin> skin;
    protected List<Message> message;
    @XmlElement(required = true)
    protected User user;

    /**
     * Gets the value of the environment property.
     * 
     * @return
     *     possible object is
     *     {@link Environment }
     *     
     */
    public Environment getEnvironment() {
        return environment;
    }

    /**
     * Sets the value of the environment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Environment }
     *     
     */
    public void setEnvironment(Environment value) {
        this.environment = value;
    }

    /**
     * Gets the value of the skin property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the skin property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSkin().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Data.Skin }
     * 
     * 
     */
    public List<Data.Skin> getSkin() {
        if (skin == null) {
            skin = new ArrayList<Data.Skin>();
        }
        return this.skin;
    }

    /**
     * Gets the value of the message property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the message property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMessage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Message }
     * 
     * 
     */
    public List<Message> getMessage() {
        if (message == null) {
            message = new ArrayList<Message>();
        }
        return this.message;
    }

    /**
     * Gets the value of the user property.
     * 
     * @return
     *     possible object is
     *     {@link User }
     *     
     */
    public User getUser() {
        return user;
    }

    /**
     * Sets the value of the user property.
     * 
     * @param value
     *     allowed object is
     *     {@link User }
     *     
     */
    public void setUser(User value) {
        this.user = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="creationTimestamp" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="editable" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *         &lt;element name="skinUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="skinSelector" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="skinCssOverrides" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="role" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                   &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="fkCalendarId" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="deleted" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id",
        "creationTimestamp",
        "title",
        "editable",
        "skinUrl",
        "skinSelector",
        "skinCssOverrides",
        "role",
        "deleted"
    })
    public static class Skin {

        protected long id;
        @XmlElement(required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar creationTimestamp;
        @XmlElement(required = true)
        protected String title;
        protected boolean editable;
        @XmlElement(required = true)
        protected String skinUrl;
        @XmlElement(required = true)
        protected String skinSelector;
        @XmlElement(required = true)
        protected String skinCssOverrides;
        protected List<Data.Skin.Role> role;
        protected boolean deleted;

        /**
         * Gets the value of the id property.
         * 
         */
        public long getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         */
        public void setId(long value) {
            this.id = value;
        }

        /**
         * Gets the value of the creationTimestamp property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getCreationTimestamp() {
            return creationTimestamp;
        }

        /**
         * Sets the value of the creationTimestamp property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setCreationTimestamp(XMLGregorianCalendar value) {
            this.creationTimestamp = value;
        }

        /**
         * Gets the value of the title property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTitle() {
            return title;
        }

        /**
         * Sets the value of the title property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTitle(String value) {
            this.title = value;
        }

        /**
         * Gets the value of the editable property.
         * 
         */
        public boolean isEditable() {
            return editable;
        }

        /**
         * Sets the value of the editable property.
         * 
         */
        public void setEditable(boolean value) {
            this.editable = value;
        }

        /**
         * Gets the value of the skinUrl property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSkinUrl() {
            return skinUrl;
        }

        /**
         * Sets the value of the skinUrl property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSkinUrl(String value) {
            this.skinUrl = value;
        }

        /**
         * Gets the value of the skinSelector property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSkinSelector() {
            return skinSelector;
        }

        /**
         * Sets the value of the skinSelector property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSkinSelector(String value) {
            this.skinSelector = value;
        }

        /**
         * Gets the value of the skinCssOverrides property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSkinCssOverrides() {
            return skinCssOverrides;
        }

        /**
         * Sets the value of the skinCssOverrides property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSkinCssOverrides(String value) {
            this.skinCssOverrides = value;
        }

        /**
         * Gets the value of the role property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the role property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRole().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Data.Skin.Role }
         * 
         * 
         */
        public List<Data.Skin.Role> getRole() {
            if (role == null) {
                role = new ArrayList<Data.Skin.Role>();
            }
            return this.role;
        }

        /**
         * Gets the value of the deleted property.
         * 
         */
        public boolean isDeleted() {
            return deleted;
        }

        /**
         * Sets the value of the deleted property.
         * 
         */
        public void setDeleted(boolean value) {
            this.deleted = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="fkCalendarId" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "id",
            "type",
            "email",
            "fkCalendarId"
        })
        public static class Role {

            protected long id;
            @XmlElement(required = true)
            protected String type;
            @XmlElement(required = true)
            protected String email;
            protected long fkCalendarId;

            /**
             * Gets the value of the id property.
             * 
             */
            public long getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             */
            public void setId(long value) {
                this.id = value;
            }

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setType(String value) {
                this.type = value;
            }

            /**
             * Gets the value of the email property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEmail() {
                return email;
            }

            /**
             * Sets the value of the email property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEmail(String value) {
                this.email = value;
            }

            /**
             * Gets the value of the fkCalendarId property.
             * 
             */
            public long getFkCalendarId() {
                return fkCalendarId;
            }

            /**
             * Sets the value of the fkCalendarId property.
             * 
             */
            public void setFkCalendarId(long value) {
                this.fkCalendarId = value;
            }

        }

    }

}
